# Advance Python Notes

### Content 

1. [In-build and Custom Generators](./generator.md)
2. [Modules in Python]()
    1. [Argeparse Module](./argparse.md)
    2. [Request Module]()
    3. [JSON module](./JSON.md)
    4. [Regular expression (re) module](./RE.md)
    5. [BeautifulSoup](./Beautiful_Soup.md)
3. [Decorators in Python]()
5. [Usefull functions]()
    1. [Enumerate]()
    2. [zip]()
    3. [map]()
    4. [reduce]()
6. [Muliprocessing or Multi threading]()
7. [Object Oriented Programming](./oopm.md)
    1. [ \__init__ (Constructor) ]()
    2. [Inheritance]()
        1. [Introduction]()
        2. [super method]()
    3. [Operator Overloading]()
    4. [Special methods]()
        1. [dir method]()
        2. [\__next__]()
        3. [\__iter__]()
        4. [\__str__]()
        5. [\__repr__]()
8. [Miscellaneous Features]()
    1. [with as]()
    2. [yield]()
    3. [lambda]()
    4. [.format function]()
    5. [ logging in python]()
    6. [args and kwargs]()
